#!/bin/bash

# ===============================================
# System Management
# ===============================================

# pacman
# -------------------------------------
alias pacman='sudo pacman --color auto'

# pacman and yay updates
alias update='sudo pacman -Syyu'
alias pksyua="yay -Syu --noconfirm"  # yay as aur helper - updates everything

# remove orphan packages
alias cleanup='sudo pacman -Rns $(pacman -Qtdq)'

# last 100 installed packages
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -100"

# -------------------------------------

# grub
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"

# processes
alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"

# hardware info
alias hw="hwinfo --short"

# merge X configs
alias loadX="xrdb -I$HOME ~/.Xresources"
alias mergeX="xrdb -merge ~/.Xresources"


# ===============================================
# Usability
# ===============================================
# Fix obvious typo's
alias cd..='cd ..'
alias pdw="pwd"

# Readable Outputs
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias df='df -h'


# ===============================================
# Other
# ===============================================
alias cmatrix='cmatrix -u 3 -C red'

