#!/bin/bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# ===============================================
# Shell Options
# ===============================================
shopt -s autocd         # change to named directory
shopt -s checkwinsize   # rearrange lines on window resize
shopt -s histappend     # do not overwrite history.
shopt -s cmdhist        # save multi-line commands as single line.
shopt -s cdspell        # autocorrects cd misspellings
shopt -s dirspell       # corrects dirs during word completion.
shopt -s expand_aliases # expand aliases.
shopt -s dotglob        # include '.*' filenames in expansions. 

# ignore duplicates and commands starting with spaces
export HISTCONTROL=ignoredups:ignorespace

# Set the default editor to vim.
export EDITOR=vim


# ===============================================
# External configurations
# ===============================================

# Enable programmable completion features.
if [ -f /usr/share/bash-completion/bash_completion ]; then
    source /usr/share/bash-completion/bash_completion
fi

# Prompt for bash and git  
if [ -f ~/.dotfiles/bash/prompt ]; then
    source ~/.dotfiles/bash/prompt
fi

# Add bash aliases.
if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

# fuzzy matcher 
# https://github.com/junegunn/fzf
# [ -f ~/.fzf.bash ] && source ~/.fzf.bash
