#!/bin/sh

# Add some more custom software to PATH.
if [ -f ~/usr/bin ]; then
    PATH=$PATH:~/usr/bin
    export PATH
fi

# Make sure pkg-config can find self-compiled software
# and libraries (installed to ~/usr)
if [ -f ~/usr/lib/pkgconfig ]; then
    PKG_CONFIG_PATH=$PKG_CONFIG_PATH:~/usr/lib/pkgconfig
    export PKG_CONFIG_PATH
fi

# Libraries
if [ -f ~/usr/lib ]; then
    # Add custom compiled libraries to library search path.
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/usr/lib
    export LD_LIBRARY_PATH

    # Add custom compiled libraries to library run path.
    LD_RUN_PATH=$LD_RUN_PATH:~/usr/lib
    export LD_RUN_PATH
fi

# # Add custom Python modules to the Python path.
# if [ -f ~/usr/lib/python2.5/site-packages ]; then
#     PYTHONPATH=$PYTHONPATH:~/usr/lib/python2.5/site-packages
#     export PYTHONPATH
# fi

