#!/bin/bash
# prompt for bash: shows username, machine git
#
# you can enable/disable:
# - username
# - machine name
# - location
# - prompt symbol
# - git features
#   - branch name
#   - branch status
#

function __prompt_bold  { echo "\[$(tput bold)\]";    }
function __prompt_reset { echo "\[$(tput sgr0)\]"; }

function __prompt_username {
    echo "$(__prompt_bold)\u"
}

__prompt_command() {
    PS1="$(__prompt_username) $ $(__prompt_reset)"
}
PROMPT_COMMAND=__prompt_command


# export PS1='\[$(tput bold)\]\[$(tput setaf 1)\][\[$(tput setaf 3)\]\u\[$(tput setaf 2)\]@\[$(tput setaf 4)\]\h \[$(tput setaf 5)\]\W\[$(tput setaf 1)\]]\[$(tput setaf 7)\]$(git status &>/dev/null;\
# if [ $? -eq 0 ]; then \
#   echo "$(echo `git status` | grep "nothing to commit" > /dev/null 2>&1; \
#   if [ "$?" -eq "0" ]; then \
#     echo "\[\033[0;32m\]"$(__git_ps1 " (%s)"); \
#   else \
#     echo "\[\033[0;91m\]"$(__git_ps1 " {%s}"); \
#   fi) \[$(tput setaf 7)\]\\$ \[$(tput sgr0)\]"; \
# else \
#   echo "\[$(tput setaf 7)\]\\$ \[$(tput sgr0)\]"; \
# fi)'
